### ISSUE TITLE
OFFSCREENCANVAS_SUPPORT

### ISSUE THREAD

**Issue by ieremius** [pongasoft/emscripten-glfw#11] opened 2024-12-23 18:46 UTC
This is sort of an add-on to Issue #9.
See also (just for the sake of interest/comparison) Emscripten Issue #19274: [Feature Request: USE_GLFW + PROXY_TO_PTHREAD + OFFSCREENCANVAS_SUPPORT](https://github.com/emscripten-core/emscripten/issues/19274) (about the old Emscripten GLFW)
Also see Emscripten test_webgl_offscreen_canvas_in_proxied_pthread() which tests the requirement outside the context of GLFW. (Except imagine that test didn't use -sASYNCIFY, which is an unwanted complication - this is easily fixed by using emscripten_set_main_loop_arg()).
 
The problem:
Using example_pthread, we can replace jsRenderFrame as follows -  this works, because of proxying to the main browser thread:
void gljsRenderFrame(GLFWwindow *glfwWindow, int w, int h, int fw, int fh, double mx, double my, int color, char const *c1, char const *c2)
{
    MAIN_THREAD_EM_ASM(
    {
      GLctx.clear($0);
      var c = $1/255.0;
      GLctx.clearColor(c, c, c, 1);
    }, GL_COLOR_BUFFER_BIT, color);
}

However, replacing with the following not work, because execution is not proxied to the main thread:
void glRenderFrame(GLFWwindow *glfwWindow, int w, int h, int fw, int fh, double mx, double my, int color, char const *c1, char const *c2)
{
  float colorf = color/255.0f;
  glClearColor(colorf, colorf, colorf, 1);
  glClear(GL_COLOR_BUFFER_BIT);
}

Exception:
    index.js:410 TypeError: Cannot read properties of undefined (reading 'clearColor')
    at _glClearColor (http://localhost:6931/source/repos/emscripten-glfw/examples/example_pthread/build/index.js:4503:49)
    at index.wasm.glRenderFrame(GLFWwindow*, int, int, int, int, double, double, int, char const*, char const*) (http://localhost:6931/source/repos/emscripten-glfw/examples/example_pthread/build/index.wasm:wasm-function[70]:0x2104)
    at index.wasm.__original_main (http://localhost:6931/source/repos/emscripten-glfw/examples/example_pthread/build/index.wasm:wasm-function[82]:0x2f44)
    at index.wasm._main_thread (http://localhost:6931/source/repos/emscripten-glfw/examples/example_pthread/build/index.wasm:wasm-function[590]:0x14712)
    at invokeEntryPoint (http://localhost:6931/source/repos/emscripten-glfw/examples/example_pthread/build/index.js:1706:42)
    at handleMessage (http://localhost:6931/source/repos/emscripten-glfw/examples/example_pthread/build/index.js:495:12)

The desire is to be able to make gl* calls from C++ in the pthreads that run our C++ main() and execute our render function specified with emscripten_set_main_loop_arg(), without proxying, using OffscreenCanvas.

**Comment by ieremius** [comment] 2024-12-23 19:02
@ypujante I discovered a few complications getting this to work, which you can see in my [fork](https://github.com/ieremius/emscripten-glfw-pthread) of your repo. The work is not done and your expertise might reveal it's simpler or should be different. However all your existing demos in their old ways still work, with the exception noted on example_minimal. And the example I added works with OffscreenCanvas, except there are some glitches entering/exiting fullscreen, and exiting.

Three sets of function calls seemed to need modified to leverage where Emscripten has added offscreen canvas support in their code.
1. emscripten_webgl_create_context/emscripten_webgl_make_context_current, as opposed to GL.createContext() directly
1. findCanvasEventTarget(), as a replacement for findEventTarget()
1. setCanvasElementSize()/getCanvasElementSize(), as opposed to modifying directly

**Comment by ypujante** [comment] 2024-12-23 19:03
The fact that it is not working when you don't proxy to the main thread seems to be normal. The code in `glRenderFrame` is your code, and it makes call into the open gl layer which has nothing to do with GLFW. If you call GLFW API in this function, whether on the main thread or not it should work. When you call `glClearColor` it is not going through any code path in this library, so I don't really have control over that. The only code that is related to openGL in the GLFW API is `glfwMakeContextCurrent` and `glfwGetCurrentContext` (as well as creating the initial opengl context when a window is created). These APIs should just work in any thread after the changes I made for pthread.

I honestly don't think there is anything I can do (besides adding support for pthread which I already did), but I would be more than happy to implement any additional features if you guide me.

Maybe I am missing something. Please let me know.

**Comment by ypujante** [comment] 2024-12-23 19:32
I just did check the changes you made on the branch and I see that there are changes to support Offscreen canvas. 

First glance, is that I am not sure that we can replace `findEventTarget` with `findCanvasEventTarget` because the change you make in the minimal example is broken without this change and that is not really an option unfortunately. It is also unclear why this change is necessary for your code to work in the first place.

I will need time to look at it further and understand. But with these changes, is calling `gljsRenderFrame` from a thread that is not the main thread simply work?

**Comment by ieremius** [comment] 2024-12-23 19:41
If one has a large code base, yes, there would be the work of changing many methods to the form of gljsRenderFrame(), but more importantly, though I'm new to this, I think all that proxying of many gl calls each frame is going to be a performance issue, and I suspect OffscreenCanvas provides a big advantage there.

**Comment by ieremius** [comment] 2024-12-23 19:58
A bit more info...if I add `-sOFFSCREENCANVAS_SUPPORT` (and `-sOFFSCREENCANVASES_TO_PTHREAD='canvas'`) to example_pthread, I get the first of a sequence of errors I was seeing last week (before that example existed). These errors are in the course of `glfwInit()`, `glfwCreateWindow()`, and `glfwMakeContextCurrent()`.

First I get the following error:
`Uncaught (in promise) InvalidStateError: Failed to set the 'width' property on 'HTMLCanvasElement': Cannot resize canvas after call to transferControlToOffscreen().`
This pertains to item 3. above, and using `setCanvasElementSize()`/`getCanvasElementSize()`.

I think the next error after that was the one I was seeing that drove the `findCanvasEventTarget()` change. Yes, I didn't imagine you would like that one, and if I was mistaken and that's not necessary, all the better!

Finally one arrives at GL context related items:
`index.js:2541 Uncaught (in promise) InvalidStateError: Failed to execute 'getContext' on 'HTMLCanvasElement': Cannot get context from a canvas that has transferred its control to offscreen.
`
Which was the motivation for using `emscripten_webgl_create_context()`/`emscripten_webgl_make_context_current`.

**Comment by ypujante** [comment] 2024-12-24 16:25
I just wanted to point out one thing about OpenGL. By default, the GLFW API creates the OpenGL context for you and my implementation does use the `GL.createContext` call directly. Not being very familiar with these APIs, I believe I simply copied what the `library_glfw.js` was doing. I didn't really know about the `emscripten_webgl_create_context` APIs in the first place. It might be better to call these official APIs in any case.

Also you can entirely opt out of having GLFW create the OpenGL context for you as most of the examples do by calling `glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);` and then calling `emscripten_webgl_create_context`. What I mean by that, in that in your experiments, you don't have to modify this library.. you can simply bypass it.

I will take a deeper look at `emscripten_webgl_create_context` and offscreen canvas.

**Comment by ypujante** [comment] 2024-12-24 16:31
I also noticed that there is a bunch of attributes that can be set like [proxyContextToMainThread](https://emscripten.org/docs/api_reference/tml5.h.html#c.EmscriptenWebGLContextAttributes.proxyContextToMainThread). Maybe that can help you?

**Comment by ieremius** [comment] 2024-12-24 20:58
I read that proxyContentToMainThread documentation again just now. Kinda confusing. But in my case it's getting initialized with `EMSCRIPTEN_WEBGL_CONTEXT_PROXY_FALLBACK`:

```
void emscripten_webgl_init_context_attributes(EmscriptenWebGLContextAttributes *attributes) {
...
  // Default context initialization state (user can override):
  // - if main thread is creating the context, default to the context not being
  //   shared between threads - enabling sharing has performance overhead,
  //   because it forces the context to be OffscreenCanvas or
  //   OffscreenFramebuffer.
  // - if a web worker is creating the context, default to using OffscreenCanvas
  //   if available, or proxying via Offscreen Framebuffer if not
  if (!emscripten_is_main_runtime_thread()) {
    attributes->proxyContextToMainThread = EMSCRIPTEN_WEBGL_CONTEXT_PROXY_FALLBACK;
  }
}
```
The doc says, "If you would like to prefer to create a higher performance OffscreenCanvas context whenever supported by the browser, but only fall back to a proxied WebGL context to keep compatibility with browsers that do not yet have OffscreenCanvas support, you can specify the EMSCRIPTEN_WEBGL_CONTEXT_PROXY_FALLBACK context creation flag. In order to use this flag, code should be compiled with both -sOFFSCREEN_FRAMEBUFFER and -sOFFSCREENCANVAS_SUPPORT linker flags."

That might be fine, but mostly we we only want to support "higher performance OffscreenCanvas" (and the devices/browsers I've tested that we care about have this support). So maybe we'd rather use `EMSCRIPTEN_WEBGL_CONTEXT_PROXY_DISALLOW` and display a message or provide some other experience if `emscripten_supports_offscreencanvas()` returns `false`.

The more I've read about it and used it, the more convinced I am that OffscreenCanvas is the best option for us - detaching rendering from anything to do with the DOM and main browser thread.

**Comment by ypujante** [comment] 2024-12-26 14:59
I am having a bit of a hard time to know what I am supposed to do in my library to support offscreen canvas, which I think is what you want. I can certainly try to use `emscripten_webgl_create_context` instead of creating the context directly, but I am not sure if that is enough. I can definitely see that this implementation is having different paths for offscreen canvas support...

I think it would help me tremendously if you could copy the `example_pthread` code into a new `example_offscreen_canvas` and write the code that you would want to implement as a user. That way it gives me a starting point/example I can work with.

Thanks

**Comment by ieremius** [comment] 2024-12-26 17:18
Sure, here it is. 

[example_offscreen_canvas.zip](https://github.com/user-attachments/files/18254111/example_offscreen_canvas.zip)
I omitted the creation of the two test threads (from example_pthread) for clarity, since offscreen canvas is inherently using pthread.

Yes, supporting offscreen canvas with emscripten-glfw is what I'm interested in. In particular this means that if I add the Emscripten OFFSCREEN_CANVAS linker flag when using emscripten-glfw, the desired behavior is that:
1. initialization including `glfwCreateWindow()` works
1. `glfwMakeContextCurrent()` works (I see your point that I can call emscripten gl context methods directly, but it's advantageous to do this all through GLFW which we were already using in Windows. This is in an effort to not have yet more #ifdefs or other such mechanisms in our code. It's convenient that all the GLFW related stuff in our codebase compiled/linked without any changes (except for some Monitor stuff).)
1. subsequent canvas resizing features work
1. there might be other canvas specific things, though I don't know of anything currently. In principle it would be ideal if your test/demo to worked in OffScreenCanvas mode. I tried to get that working in my fork but it wasn't fast due to my lack of experience with cmake and web development/JavaScript generally so I haven't had time for that yet.

I also see your point that details of rendering are outside the scope of your library. However it's been my experience that after changes I made in my fork and what I've done so far so far using that in our product that gl* calls just work as-is using this methdology, which is also very advantageous.

WRT, "I can definitely see that this implementation is having different paths for offscreen canvas support", FWIW, the canvas sizing and gl context changes I made in my fork seems to work fine WRT all your existing demos. There was that one thing noted in example_minimal WRT findCanvasEventTarget(). Maybe a different path is required in that case.

FWIW, it appears that if OffscreenCanvas were supported by emscripten-glfw this would be an additional good differentiator for your table in Usage.md. And it provides a pretty clear porting path for a certain type of application.

Incidentally I've found the linker flag -sGL_DEBUG to be helpful with regard to working with OffscreenCanvas.

**Comment by ypujante** [comment] 2024-12-27 14:17
Thank you. I will take a look at your example. 

I created a [branch](https://github.com/pongasoft/emscripten-glfw/tree/offscreen-canvas) for this effort. I have made the changes to call `emscripten_webgl_create_context` instead of hardcoding the creation.

Without any other modifications, the demo/test and all examples are still working, including the minimal example.

I believe the minimal example will never work as-is if it is compiled with offscreen canvas support, because the code [here](https://github.com/emscripten-core/emscripten/blob/b94d6e6ced33576a1ad96c7f6e701788c6f49211/src/library_html5.js#L347) (which is a bit convoluted), has a different branch when `OFFSCREENCANVAS_SUPPORT` is defined and does not use `specialHTMLTargets` which is where the default selector (`Module['canvas']`)) is handled.

I don't think this is an issue as working with `OFFSCREENCANVAS_SUPPORT` is an advanced feature and needs to be explicitly enabled. So the fact that the minimal example (or any app relying on the default selector) would need to be modified (as you did to "fix" the issue) when compiling with `OFFSCREENCANVAS_SUPPORT` is fine as long as no changes are required when not using this option (which is working as of this branch).

**Comment by ypujante** [comment] 2024-12-27 18:43
I pushed another update to the branch which

* adds `example_offscreen_canvas`
* fixes the issues you were seeing when resizing when `OFFSCREENCANVAS_SUPPORT` is on

You can see the change in [lib_emscripten_glfw3.js](https://github.com/pongasoft/emscripten-glfw/blob/8f9e52fff43115b68389219e4054b6c67b250696/src/js/lib_emscripten_glfw3.js#L586) which detects that it is being run in this mode and delegate to the built-in `_emscripten_set_canvas_element_size` which takes care of applying the width/height to the offscreen canvas instead...

As far as I can tell, there is no issue when resizing the canvas (when resizing the browser window) or going fullscreen.

I hacked around the demo to do something similar and it also seems to be working fine.

Let me know if you can test it and if that is what you wanted in the first place.

**Comment by ieremius** [comment] 2024-12-27 19:54
Awesome. I might be away from the computer for the rest of today, but if so I'll test it first thing tomorrow morning at the latest.

**Comment by ieremius** [comment] 2024-12-27 20:05
You might like this - it's up to you - these Emscripten methods getCanvasElementSize() and setCanvasElementSize() worked for me in my fork with or without offscreen canvas so avoids an #ifdef:

//! emscripten_glfw3_window_set_size
  emscripten_glfw3_window_set_size__proxy: 'sync',
  emscripten_glfw3_window_set_size: (glfwWindow, width, height, fbWidth, fbHeight) => {
    const ctx = GLFW3.fWindowContexts[glfwWindow];
    const canvas = ctx.canvas;

    const [currentCanvasWidth, currentCanvasHeight] = getCanvasElementSize(canvas);
    if (currentCanvasWidth != fbWidth || currentCanvasHeight != fbHeight)
      setCanvasElementSize(canvas, fbWidth, fbHeight)
      
    // this will (on purpose) override any css setting
    ctx.setCSSValue("width",   width + "px", "important");
    ctx.setCSSValue("height", height + "px", "important");

    if(ctx.fCanvasResize && ctx.fCanvasResize.onSizeChanged)
      ctx.fCanvasResize.onSizeChanged(width, height);
  },

**Comment by ieremius** [comment] 2024-12-28 01:55
@ypujante, "Let me know if you can test it and if that is what you wanted in the first place." I tested it and it works and definitely is what I wanted!

I see a glitch when exiting fullscreen with the rendering overflowing the canvas until I drag/size the browser window. And a similar thing when exiting with Ctrl-Q. I see some messages in the console about autoResizeViewport - it might be a lack of viewport sizing in the demo code I provided. I can look at that some more in the morning.

Interestingly it's rendering at 300 FPS, the refresh rate of my monitor. (Not a problem :) I'm on a different computer this week - last week it was running at 60 FPS which I think of as typical for a browser.

Thanks!

**Comment by ieremius** [comment] 2024-12-28 02:49
> You might like this - it's up to you - these Emscripten methods getCanvasElementSize() and setCanvasElementSize() worked for me in my fork with or without offscreen canvas so avoids an #ifdef:
> 
> ```
>   emscripten_glfw3_window_set_size__proxy: 'sync',
>   emscripten_glfw3_window_set_size: (glfwWindow, width, height, fbWidth, fbHeight) => {
>     const ctx = GLFW3.fWindowContexts[glfwWindow];
>     const canvas = ctx.canvas;
> 
>     const [currentCanvasWidth, currentCanvasHeight] = getCanvasElementSize(canvas);
>     if (currentCanvasWidth != fbWidth || currentCanvasHeight != fbHeight)
>       setCanvasElementSize(canvas, fbWidth, fbHeight)
>       
>     // this will (on purpose) override any css setting
>     ctx.setCSSValue("width",   width + "px", "important");
>     ctx.setCSSValue("height", height + "px", "important");
> 
>     if(ctx.fCanvasResize && ctx.fCanvasResize.onSizeChanged)
>       ctx.fCanvasResize.onSizeChanged(width, height);
>   },```
> ```

Never mind, I looked at this again and I see these use findCanvasEventTarget() and now I remember this is how I waded into the specialHTMLTargets problem in the first place.

**Comment by ypujante** [comment] 2024-12-28 17:41
I can reproduce the "exit fullscreen glitch" but only on Firefox. It works fine with Safari and Chrome. Also works fine on Firefox using the `example_resizable_container` (which `example_offscreen_canvas` is based off). I think the "quit" glitch is related to "exit fullscreen glitch".

Putting log statement/stack traces in my code, I can definitely see that Firefox triggers the observer (on the outside div no less!) **before** entering fullscreen with a bogus size which then gets recorded as the "size before entering fullscreen" and then restored when exiting fullscreen. Not sure if this is a Firefox bug.

In regards to calling `setCanvasElementSize`, since it is an internal API, I much prefer not to. Calling `_emscripten_set_canvas_element_size` is the officially supported external/C API (the fact that it starts with an `_` is how C function are treated from Javascript, hence having to transform the selector into a C string before calling and free after...)

**Comment by ypujante** [comment] 2024-12-28 18:47
I pushed a fix for the "exit fullscreen" glitch. I really think that there is a problem with Firefox, but since it was easy to capture the size on request instead of waiting for the callback, and it works for the all the other examples/demo, then I think it is fine.

**Comment by ieremius** [comment] 2024-12-28 18:49
Interesting...I also added a log message in _emscripten_glfw3_window_set_size() and see a bogus size on the way to fullscreen. And it's the same bogus size on both browsers - 1440x540 - in my case. On Firefox exiting fullscreen it uses that first, but then it gets sized again to the correct size. On Chrome it stays the incorrect size.

I'll try your fix and hopefully that'll fix my Chrome case.

I totally get what you mean about _emscripten_glfw3_window_set_size(). Also my forgetting about how setCanvasElementSize() worked was causing a disconnect and some confusion.

**Comment by ieremius** [comment] 2024-12-29 02:49
Your fix for "exit fullscreen" fixed the Chrome case I was seeing.

The "quit" glitch remains on both Firefox and Chrome, just FYI. Are you still seeing that?

**Comment by ypujante** [comment] 2024-12-29 17:08
I pushed another fix for the "quit" glitch. But it is in the example itself, not the library.

I think what is going on is that `glfwTerminate` [properly calls](https://github.com/pongasoft/emscripten-glfw/blob/358f5765a8e38456c82c2dc98d1486e5311aeabd/src/js/lib_emscripten_glfw3.js#L555) the api to reset the size of the canvas to its size prior to associating it to a glfw window, but due to the async nature of this call, it does not get executed when `emscripten_cancel_main_loop` is called right away. [Deferring](https://github.com/pongasoft/emscripten-glfw/blob/cdad068d045a3cf0be727a0a2167d69c0ea0aba5/examples/example_offscreen_canvas/main.cpp#L60) it to the next frame/loop, fixes the issue.

**Comment by ieremius** [comment] 2024-12-29 19:00
Oh good makes sense. Sorry I didn't get a chance to help figure that out.

I don't know of anything else that needs to be done. Thanks again. This is very helpful and has been educational as well.

**Comment by ypujante** [comment] 2024-12-29 19:02
If you are satisfied with it, I will do a little bit more testing (like in Release mode with optimization for example) and if everything looks good I will merge to master and release it.

**Comment by ieremius** [comment] 2024-12-29 19:05
Sounds good to me.

**Comment by ypujante** [comment] 2024-12-30 17:03
The changes have been pushed to `master` and [released](https://github.com/pongasoft/emscripten-glfw/releases/tag/v3.4.0.20241230).

I have submitted a [PR](https://github.com/emscripten-core/emscripten/pull/23259) in Emscripten to push these changes the contrib port.

**Closed by ypujante** 2024-12-30 17:03 UTC
